### PR TITLE
only small and medium seed 30

### PR DESCRIPTION
**Pull request by smilesun**

### CODE REVIEW

**Comment by smilesun** [comment]
uv run snakemake --rerun-incomplete -j 10

**Comment by smilesun** [comment]
it shows 8 of 28 steps undone, which  I thought should be only 8 steps=725-717

**Comment by smilesun** [comment]
not sure if there is infinite loop somewhere, again it does not go forward with 8 jobs left:

```
Mon Dec 23 10:46:51 2024]
localrule evaluate_anc_acc:
    input: results/datasets/method=standard/graph_size=medium/seed=4/samp_size=1000/ground_truth_dag.pkl, results/datasets/method=standard/graph_size=medium/seed=4/samp_size=1000/hidden_nodes.csv, results/est/alg=linlam/method=standard/graph_size=medium/seed=4/samp_size=1000/causal_order.csv
    output: results/eval/alg=linlam/method=standard/graph_size=medium/seed=4/samp_size=1000/anc_acc.csv
    jobid: 553
    reason: Input files updated by another job: results/est/alg=linlam/method=standard/graph_size=medium/seed=4/samp_size=1000/causal_order.csv
    wildcards: alg=linlam, method=standard, graph_size=medium, seed=4, samp_size=1000
    resources: tmpdir=/tmp

[Mon Dec 23 10:46:52 2024]
Finished job 553.
20 of 28 steps (71%) done

```

**Comment by Alex-Markham** [comment]
What 8 jobs aren't being run? Right after calling snakemake, it should show a summary of which jobs it will run. Maybe looking at that helps to debug?


--
Alex Markham (pronouns: they/them)
Postdoc, Copenhagen Causality Lab
Dept. of Mathematical Sciences
University of Copenhagen


________________________________

**Comment by smilesun** [comment]
```
ake --rerun-incomplete -j 10                                             
Assuming unrestricted shared filesystem usage.                           
host: sunxd-ThinkPad-P1-Gen-4i                                           
Building DAG of jobs...                                                  
Using shell: /usr/bin/bash                                               
Provided cores: 10 
Rules claiming more threads will be scaled down.
Job stats:
job                 count
----------------  -------
all                     1
boxplot_acc             1
boxplot_acc_csv         1
boxplot_shd             1
boxplot_shd_csv         1
evaluate_anc_acc       11
evaluate_shd            1
fit_fci                 1
fit_linlam             10
total                  28

Select jobs to execute...
Execute 10 jobs... 


```

**Comment by smilesun** [comment]
it does not really show which job is runing at the moment  ( the blocking job), since jib 553 was done more than 1 hour ago, it does not show which job is being run.

**Comment by smilesun** [comment]
snakemake --detailed-summary
[detailed_summary.txt](https://github.com/user-attachments/files/18228638/detailed_summary.txt)

**Comment by smilesun** [comment]
it turns out somehow seed 20 has a problem when fitting FCI, with dea2d0f seed 20 is excluded

**Pull request merged**
